spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://mysql.coffit.today:3306/samjo
    username: samjo
    password: samjo
  servlet:
    multipart:
      enabled: true
      location: C:/thymeleaf-springboot/

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

  freemarker:
    cache: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

    logging:
      level:
        root: info


mybatis:
  # mapper.xml location Setting
  mapper-locations: mybatis/mapper/*.xml
  # alias Setting
  configuration:
    map-underscore-to-camel-case: true
