spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/samjo
    username: samjo
    password: samjo
  servlet:
    multipart:
      enabled: true
      location: C:/thymeleaf-springboot/

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

  freemarker:
    cache: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

